name: mlproj
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  
  # Core ML and Computer Vision (conda packages for better compatibility)
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - opencv>=4.6.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - scikit-learn>=1.1.0
  - pandas>=1.4.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pillow>=9.0.0
  - h5py>=3.7.0
  - pyyaml>=6.0
  - tqdm>=4.64.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - pytest>=7.1.0
  - dlib>=19.24.0  # Better to install via conda on macOS
  
  # pip-only packages
  - pip:
    - tensorflow>=2.10.0
    - mediapipe>=0.9.0
    - albumentations>=1.3.0
    - imgaug>=0.4.0
    - timm>=0.6.0
    - transformers>=4.20.0
    - torchmetrics>=0.9.0
    - pytorch-lightning>=1.7.0
    - mat73>=0.59
    - pycocotools>=2.0.4
    - plotly>=5.10.0
    - wandb>=0.13.0
    - streamlit>=1.12.0
    - gradio>=3.4.0
    - flask>=2.2.0
    - websockets>=10.3
    - face-recognition>=1.3.0
    - mtcnn>=0.1.1
    - facenet-pytorch>=2.5.2
    - click>=8.1.0
    - python-dotenv>=0.20.0
    - colorlog>=6.7.0
    - pytest-cov>=3.0.0
    - black>=22.6.0
    - flake8>=5.0.0
    - mypy>=0.971
    - ipywidgets>=8.0.0
    - imageio>=2.21.0
    - imageio-ffmpeg>=0.4.7
    - moviepy>=1.0.3
    - onnx>=1.12.0
    - onnxruntime>=1.12.0
    - pygame>=2.1.0
    - pyautogui>=0.9.53
    - hydra-core>=1.2.0
    - omegaconf>=2.2.0
    - loguru>=0.6.0
